"""update repository schema

Revision ID: 31e8cf0f275b
Revises: 86a442447c20
Create Date: 2026-09-06 20:10:13.188085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e8cf0f275b'
down_revision: Union[str, Sequence[str], None] = '86a442447c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'provider',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('repositories', 'clone_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_unique_constraint('uq_repositories_project_external_id', 'repositories', ['project_id', 'external_id'])
    op.drop_constraint(op.f('repositories_project_id_fkey'), 'repositories', type_='foreignkey')
    op.create_foreign_key(None, 'repositories', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('repositories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.create_foreign_key(op.f('repositories_project_id_fkey'), 'repositories', 'projects', ['project_id'], ['id'])
    op.drop_constraint('uq_repositories_project_external_id', 'repositories', type_='unique')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.alter_column('repositories', 'clone_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('repositories', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
